name: BreachCore
version: 1.0
main: net.breachmc.breachcore.Main
authors: [Experminator, ProtocollWeb]
commands:
  breachcore:
    description: Base Command of BreachCore
    aliases: [bc, breach, core]